# Exercices 

**Reminder**

* Chacune de vos fonctions doit être testée. 

* Chaque cellule doit compiler. 

* Si le résultat n'est pas celui voulu, expliquer ce qui semble ne pas aller dans votre fonction en commentaires. 

### Ecrire une fonction qui prend une liste de mots et retourne le plus long. Gérer le cas où la liste ne contient pas que des strings.

In [3]:
liste = ['liste', 'de', 'mots', 'longs', 'et', 'moinslongue', 10, 16]

In [1]:
def plus_long_mot(liste_mots):
    list_corrigee = []
    for mot in liste_mots:
        if type(mot)==str:
            list_corrigee.append(mot)
        maximum = max(list_corrigee, key=len)
    return maximum

In [5]:
def plus_long(liste_mots):
    mot_long = ''
    for mot in liste_mots:
        if len(str(mot)) > len(mot_long):
            mot_long = mot
    return mot_long

In [6]:
plus_long(liste)

'moinslongue'

### 2. Ecrire une fonction qui ajoute une string au milieu d'une autre string.


In [ ]:
def ajouter_au_milieu(mot, ajout):


In [4]:
ajouter_au_milieu('moinslongue', ' ')

11
5


'moins longue'

### 3. Ecrire une fonction qui transforme en majuscule la première et la dernière lettre de toutes les string d'une liste.


In [24]:
def majuscules_premiere_derniere(liste_mot):
    

In [25]:
# Test
liste_mots = ["exemple", "python", "programmation"]
resultat = majuscules_premiere_derniere(liste_mots)
print(resultat)

['ExemplE', 'PythoN', 'ProgrammatioN']


### 4. Ecrire une fonction qui trouve les 3 plus hautes valeurs d'un dictionnaire.


In [36]:
def trois_plus_hautes_valeurs(dictionnaire):
    valeurs = list(dictionnaire.values())
    valeurs.sort(reverse=True)
    return valeurs[:3]

In [34]:
def trois_plus_hautes_valeurs(dico):
    print(dico.items())
    dico_tri = sorted(dico.items(), key=lambda x:x[1], reverse=True)
    print(dico_tri)
    trois_plus_hautes = [item[1] for item in dico_tri[:3]]

    return trois_plus_hautes

In [37]:
# Test
mon_dictionnaire = {'a': 10, 'b': 5, 'c': 8, 'd': 15}
resultat = trois_plus_hautes_valeurs(mon_dictionnaire)
print(resultat)

[15, 10, 8]


### 5. Ecrire une fonction qui ajoute un élément à un tuple. Idem qui enlève.


In [44]:
def ajouter_element_tuple(tuple_courant, nouvel_elem):
    return tuple_courant+(nouvel_elem,)

In [58]:
def ajouter_element_tuple(tuple_courant, nouvel_elem):
    tmp = list(tuple_courant)
    tmp.append(nouvel_elem)
    return tuple(tmp)

In [46]:
def enlever_element_tuple(tup, element):
    result = []
    for elem in tup:
        if elem != element:
            result.append(elem)
    return tuple(result)

In [57]:
# Test
tup = (1, 2, 3, 4, 2)
nouvel_element = 2
result_ajout = ajouter_element_tuple(tup, nouvel_element)
result_enlever = enlever_element_tuple(tup, nouvel_element)

print(result_ajout)  # Output: (1, 2, 3, 4, 2, 2)
print(result_enlever)  # Output: (1, 3, 4)


(1, 2, 3, 4, 2, 2)
(1, 3, 4)


### 6. Ecrire une fonction qui remplace la dernière valeur des tuples d'une liste.
	Exemple :
		entree: [(10, 20, 40), (40, 50, 60), (70, 80, 90)]
		sortie: [(10, 20, 100), (40, 50, 100), (70, 80, 100)]


In [61]:
def remplacer_derniere_valeur(liste_tuples, nouvelle_valeur):
    result = []
    for tup in liste_tuples:
        modified_tuple = tup[:-1] + (nouvelle_valeur,)
        result.append(modified_tuple)
    return result

In [63]:
# Test
entree = [(10, 20, 40), (40, 50, 60), (70, 80, 90)]
sortie = remplacer_derniere_valeur(entree, 18)
print(sortie)

[(10, 20, 18), (40, 50, 18), (70, 80, 18)]


### 7. Ecrire une fonction qui lit un csv dont les délimiteurs sont des tabulations (import csv ou pandas).


In [64]:
import pandas as pd

In [70]:
def lire_csv(path_tsv):
    return pd.read_csv(path_tsv, sep='\t')

In [71]:
tsv = lire_csv("/home/crazyjeannot/Documents/cours/2024/Python4DH/data/csv/MIS_4.tsv")

In [74]:
tsv = pd.read_csv("/home/crazyjeannot/Documents/cours/2024/Python4DH/data/csv/MIS_4.tsv", sep='\t')

In [75]:
tsv

Groupe labo  Numéro mission Missionnaire Date de départ  \
0          1198            1436     90407198     09/01/2023   
1          1198            1435     90406857     11/01/2023   
2          1198            1434     90406849     31/01/2023   
3          1198            1439        14463     02/02/2023   
4          1198            1437         4609     01/03/2023   
..          ...             ...          ...            ...   
73         1198            1486                  15/11/2023   
74         1198            1493        14463     06/12/2023   
75         1198            1492       197049     06/12/2023   
76         1198            1492       197049     07/12/2023   
77         1198            1492       197049     08/12/2023   

          Ville de départ Pays de départ Ville de destination  \
0                  VENISE         Italie                PARIS   
1                WESTERLO       Belgique                PARIS   
2   LONDRES - EAST BARNET    Royaume-Uni                PARIS   
3                   PARIS         France            CAMBRIDGE   
4   ST REMY LES CHEVREUSE         France              POTSDAM   
..                    ...            ...                  ...   
73                  Paris         France           Strasbourg   
74                  Paris         France            Villejuif   
75      Neuilly-sur-Seine         France   Le Kremlin-Bicetre   
76     Le Kremlin-Bicetre         France   Le Kremlin-Bicetre   
77     Le Kremlin-Bicetre         France   Le Kremlin-Bicetre   

   Pays de destination                Moyens de transport  \
0               France                  Avion,Train,Train   
1               France                        Train,Train   
2               France                              Train   
3          Royaume-Uni                        Avion,Train   
4            Allemagne                        Avion,Avion   
..                 ...                                ...   
73              France         Train,Transports en commun   
74              France  Micromobilité (Vélo, trottinette)   
75              France  Micromobilité (Vélo, trottinette)   
76              France  Micromobilité (Vélo, trottinette)   
77              France  Micromobilité (Vélo, trottinette)   

    Nb de pers. dans la voiture Aller / Retour  \
0                           NaN            OUI   
1                           NaN            OUI   
2                           NaN            OUI   
3                           NaN            OUI   
4                           NaN            OUI   
..                          ...            ...   
73                          NaN            NON   
74                          NaN            OUI   
75                          NaN            OUI   
76                          NaN            OUI   
77                          NaN            OUI   

                Motif du déplacement  Statut agent Date de retour  
0                             Autres           NaN     15/01/2023  
1                             Autres           NaN     11/01/2023  
2                             Autres           NaN     02/02/2023  
3        Visite, contact pour projet           NaN     19/02/2023  
4                             Autres           NaN     03/03/2023  
..                               ...           ...            ...  
73  Colloques, congrès et séminaires           NaN     17/11/2023  
74  Colloques, congrès et séminaires           NaN     08/12/2023  
75  Colloques, congrès et séminaires           NaN     06/12/2023  
76  Colloques, congrès et séminaires           NaN     07/12/2023  
77  Colloques, congrès et séminaires           NaN     08/12/2023  

[78 rows x 14 columns]

### 8. Ecrire une fonction qui écrit des dictionnaires dans un fichier (json par exemple)


In [77]:
import json

In [78]:
bureau = {'marque': "ikeu", 'matiere': "bois", 'type': "meuble", 'nom': "bureau", 'designeur': "Fernand"}
def dict_to_json():
    with open('document.json', 'w') as json_file:
        json.dump(bureau, json_file)

In [79]:
dict_to_json()

### 9. Ecrire une fonction qui convertit un array en array de float


In [82]:
import numpy as np

In [87]:
integers = np.arange(1, 15)

In [88]:
integers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [85]:
def int_to_float(array):
    for floating in array:
        floating = integers.astype(float)
    return floating

In [86]:
array_float = int_to_float(integers)

In [24]:
type(array_float)

numpy.ndarray

In [25]:
array_float

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14.])

In [92]:
float_table = integers.astype(float)

In [91]:
float_table

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14.])

### 10. Ecrire une fonction qui enregistre un array dans un fichier texte.


In [93]:
array = np.array([[8,3,2,4],[5,1,6,0],[9,7,4,1]])

In [94]:
str_array = array.astype(str)

In [95]:
str_array

array([['8', '3', '2', '4'],
       ['5', '1', '6', '0'],
       ['9', '7', '4', '1']], dtype='<U21')

In [96]:
str(array)

'[[8 3 2 4]\n [5 1 6 0]\n [9 7 4 1]]'

In [97]:
def array_to_txt_and_display(array):
    
    file = open("array_file.txt", "w+") 
  
    content = str(array) 
    file.write(content) 
    file.close() 
    
    file = open("array_file.txt", "r") 
    content = file.read() 
  
    print("\nContent in array_file.txt:\n", content) 
    file.close() 

In [98]:
array_to_txt_and_display(array)


Content in array_file.txt:
 [[8 3 2 4]
 [5 1 6 0]
 [9 7 4 1]]


### 11. Ecrire une fonction qui réalise l'addition matricielle de deux arrays. La multiplication ça se tente ?

In [101]:
import numpy as np

M = np.array([[1, 2], [3, 4]]) 
N = np.array([[4, 3], [2, 1]]) 

In [99]:
def addition_matricielle(a, b):
    return np.add(a, b)

def multiplication_matricielle(a, b):
    return np.dot(a, b)

In [102]:
addition_matricielle(M, N)

array([[5, 5],
       [5, 5]])

In [103]:
multiplication_matricielle(M, N)

array([[ 8,  5],
       [20, 13]])